In [4]:
import pandas as pd
from sqlalchemy import create_engine
import cx_Oracle

# Pre-requite database connection

oracle_engine = create_engine("oracle+cx_oracle://system:admin@localhost:1521/xe")
mysql_engine = create_engine("mysql+pymysql://root:Admin%40143@localhost:3308/retail_dwh_apr_2026")

In [5]:
foreign_query = """select * from fact_sales"""
primary_query = """select * from stag_products"""
foreign_df = pd.read_sql(foreign_query,mysql_engine)
primary_df = pd.read_sql(primary_query, mysql_engine)

In [6]:
foreign_df

    sales_id  product_id  store_id  quantity  total_sales   sale_date
0         10         110         4         9        153.0  2024-09-10
1         11         101         4        15        210.0  2024-09-11
2         12         102         5         9        243.0  2024-09-12
3         13         103         6        10        220.0  2024-09-13
4         14         104         7         8        248.0  2024-09-14
5         15         105         4        12        132.0  2024-09-15
6         16         106         5         5        115.0  2024-09-16
7         17         107         6         3         78.0  2024-09-17
8         18         108         7         6        168.0  2024-09-18
9         19         109         8        11        220.0  2024-09-19
10        20         110         9         9        175.5  2024-09-20
11        21         101         1        14        217.0  2024-09-21
12        22         102         2         8        176.0  2024-09-22
13        23         103         3         7        126.0  2024-09-23
14        24         104         4         6        150.0  2024-09-24
15        25         105         2        12        162.0  2024-09-25
16        26         106         3         5        105.0  2024-09-26
17        27         107         1        10        190.0  2024-09-27
18        28         108         5         6        162.0  2024-09-28
19        29         109         6         9        216.0  2024-09-29
20        30         110         7         7        164.5  2024-09-30
21        31         101         4        13        188.5  2024-10-01
22        32         102         5         6        174.0  2024-10-02
23        33         103         6         8        168.0  2024-10-03
24        34         104         7         5        150.0  2024-10-04
25        35         105         4         7        105.0  2024-10-05
26        36         106         5         3         75.0  2024-10-06
27        37         107         6        12        216.0  2024-10-07
28        38         108         7         9        180.0  2024-10-08
29        39         109         8        10        220.0  2024-10-09
30        40         110         9         6        156.0  2024-10-10
31        41         101         3         5         75.0  2024-10-11
32        42         102         4         4         80.0  2024-10-12
33        43         103         5         9        171.0  2024-10-13
34        44         104         6         7        196.0  2024-10-14
35        45         105         7        10        250.0  2024-10-15
36        46         106         8         8        180.0  2024-10-16
37        47         107         9         6        144.0  2024-10-17
38        48         108         1         3         81.0  2024-10-18
39        49         109         2        11        203.5  2024-10-19
40        50         110         3        12        252.0  2024-10-20
41        60         110         4         9        153.0  2024-09-10

In [8]:
primary_df

,product_id,product_name,category,price,stock_quantity,brand,rating
0,101,iPhone 15,Smartphones,999,50,Apple,4.8
1,102,Samsung Galaxy S23,Smartphones,899,75,Samsung,4.7
2,103,Dell XPS 13,Laptops,1200,30,Dell,4.6
3,104,MacBook Pro 14,Laptops,2000,25,Apple,4.9
4,105,Sony WH-1000XM5,Headphones,350,100,Sony,4.7
5,106,Nike Air Zoom,Sneakers,120,200,Nike,4.5
6,107,"Samsung 55"" TV",Electronics,700,40,Samsung,4.4
7,108,Philips Hue Bulb,Smart Home,50,500,Philips,4.8
8,109,Fitbit Charge 5,Wearables,150,150,Fitbit,4.6
9,110,Kindle Paperwhite,eReaders,130,80,Amazon,4.7

In [17]:

df = foreign_df[~foreign_df['product_id'].isin(primary_df['product_id'])]

In [26]:
assert df.empty,"There are some additional rows in foregin key column"

In [38]:
primary_df.isnull().values()

TypeError: 'numpy.ndarray' object is not callable